import { MyColors } from "../globals.slint";

import { Emoji, EmojiModel } from "./emoji.slint";

export component Preview inherits Rectangle {
    in property<EmojiModel> emoji;

    HorizontalLayout {
        alignment: start;
        height: 60px;

        padding-left: 10px;
        padding-top: 5px;
        padding-bottom: 5px;

        Text {
            width: 40px;
            font-size: 40px;
            text: root.emoji.character;
        }

        VerticalLayout {
            alignment: center;
            padding-left: 10px;

            if root.emoji.codes.length > 0: HorizontalLayout {
                alignment: start;

                for code in root.emoji.codes: Text {
                    text: code;
                    wrap: no-wrap;
                    overflow: elide;
                    font-size: 18px;
                    padding-right: 10px;
                    horizontal-alignment: left;
                    color: MyColors.foreground;
                    vertical-alignment: center;
                }
            }

            if !root.emoji.name.is-empty: Text {
                wrap: no-wrap;
                overflow: elide;
                font-size: 12px;
                text: root.emoji.name;
                horizontal-alignment: left;
                color: MyColors.foreground;
                vertical-alignment: center;
            }
        }
    }
}
