import { MyColors, MainState } from "../globals.slint";

import { ComboBox } from "./combobox.slint";
import { Input } from "./input.slint";
import { Emoji, EmojiModel } from "./emoji.slint";

@rust-attr(derive(clap::ValueEnum))
export enum SkinTone {
    Default,
    Light,
    MediumLight,
    Medium,
    MediumDark,
    Dark,
}

export global SearchGlobal {
    in-out property<SkinTone> tone: SkinTone.Default;
    in-out property<string> search-text;

    callback search(/* search */ string);
    callback change_tone(/* tone */ string);

    public pure function tone-id(tone: SkinTone) -> int {
        if tone == SkinTone.Light {
            return 1;
        }
        if tone == SkinTone.MediumLight {
            return 2;
        }
        if tone == SkinTone.Medium {
            return 3;
        }
        if tone == SkinTone.MediumDark {
            return 4;
        }
        if tone == SkinTone.Dark {
            return 5;
        }
        0
    }
}

export component Search inherits Rectangle {
    property<[string]> tones: [ "👋", "👋🏻", "👋🏼", "👋🏽", "👋🏾", "👋🏿" ];
    in-out property<string> search-terms;

    init => {
        search-input.focus();
    }

    GridLayout {
        spacing-horizontal: 15px;

        padding-left: 10px;
        padding-right: 10px;

        Row {
            Text {
                font-size: 20px;
                text: "🔎";
                vertical-alignment: center;
            }

            search-input := Input {
                text-color: MyColors.foreground;
                background: MyColors.background;

                changed text => {
                    SearchGlobal.search-text = self.text;
                    SearchGlobal.search(self.text);
                }
            }

            ComboBox {
                choices: root.tones;
                value: root.tones[SearchGlobal.tone-id(SearchGlobal.tone)];
                changed value => {
                    SearchGlobal.change_tone(self.value)
                }
            }
        }
    }
}
