export global MyColors {
    in-out property<color> background: #fff;
    in-out property<color> foreground: #000;
}

export global MainState {
    in property<bool> show-preview: false;
    in property<bool> show-search: false;
    out property<length> height: show-preview ? 390px : 330px;
    out property<length> width: 315px;
    out property<length> font-size: 20px;
    in property<string> font: "Noto Color Emoji";

    callback close();
}
