import { ListView } from "std-widgets.slint";

import { MyColors } from "./globals.slint";
import { MyColors, MainState } from "./globals.slint";
import { FocusDirection, Navigation } from "./navigation.slint";

import { Emoji, EmojiModel, EmojiHandle } from "./components/emoji.slint";
import { Tabs, TabsHandle } from "./components/tab.slint";
import { Preview } from "./components/preview.slint";
import { Search, SearchGlobal, SkinTone } from "./components/search.slint";

export { MainState, MyColors, EmojiModel, EmojiHandle, FocusDirection, Navigation, SearchGlobal, SkinTone, TabsHandle }

export component MainWindow inherits Window {
    in property<[[EmojiModel]]> emojis: [];

    callback start(length, length);

    title: "Simplemoji";
    width: MainState.width;
    height: MainState.height;
    background: MyColors.background;

    no-frame: true;
    always-on-top: true;
    default-font-size: MainState.font-size;

    init => { start(MainState.width, MainState.height) }

    VerticalLayout {
        width: root.width;
        spacing: 2px;

        Tabs {
            click() => {
                content.viewport-y = 0;
            }
        }

        if MainState.show-search: Search { }

        if MainState.show-preview && TabsHandle.emoji-preview.has: Preview {
            emoji: TabsHandle.emoji-preview.content;
        }

        HorizontalLayout {
            content := ListView {
                width: root.width;
                horizontal-scrollbar-policy: always-off;
                vertical-scrollbar-policy: always-off;

                for row in emojis: HorizontalLayout {
                    for emoji in row: Emoji {
                        emoji: emoji;
                        hover => {
                            TabsHandle.emoji-preview.has = true;
                            TabsHandle.emoji-preview.content = emoji;
                        }
                        key-pressed(event) => { Navigation.key(event) || Navigation.tab(event) }
                        click => { EmojiHandle.click(emoji.character); }
                    }
                }
            }
        }
    }
}
