import { TabsHandle } from "./api/tabs.slint";

export enum FocusDirection {
    Up,
    Down,
    Left,
    Right,
}

export global Navigation {
    callback move(FocusDirection);

    public function name(event: KeyEvent) -> string {
        if (event.text == Key.UpArrow) {
            return "UpArrow";
        }
        if (event.text == Key.DownArrow) {
            return "DownArrow";
        }
        if (event.text == Key.LeftArrow) {
            return "LeftArrow";
        }
        if (event.text == Key.RightArrow) {
            return "RightArrow";
        }
        "None"
    }

    public function tab(event: KeyEvent) -> bool {
        if (event.text == Key.Tab) {
            if event.modifiers.shift {
                TabsHandle.prev();
                return true;
            }
            TabsHandle.next();
            return true;
        }

        false
    }

    public function key(event: KeyEvent) -> bool {
        if (event.text == Key.UpArrow) {
            move(FocusDirection.Up);
            return true;
        }
        if (event.text == Key.DownArrow) {
            move(FocusDirection.Down);
            return true;
        }
        if (event.text == Key.LeftArrow) {
            move(FocusDirection.Left);
            return true;
        }
        if (event.text == Key.RightArrow) {
            move(FocusDirection.Right);
            return true;
        }

        false
    }
}
